application:
  port: 8080
  base_url: http://127.0.0.1
  hmac_secret: 5k1NQ78d9D%#*@Mb4u^05tQO1Xp0$JL90FdCrotN3tXi8sabNum1b3f!frj#K!sD

database:
  host: localhost
  port: 5432
  username: postgres
  password: password
  database_name: newsletter

email_client:
  base_url: http://localhost
  sender_email: test@example.com
  authorization_token: my-secret-token
  timeout_milliseconds: 10000

redis_url: redis://127.0.0.1:6379
