# Edit with your own configuration

application:
  port: 8080

database:
  host: localhost
  port: 5432
  username: postgres
  password: password
  database_name: newsletter

email_client:
  base_url: http://localhost
  sender_email: test@example.com
  authorization_token: my-secret-token
  timeout_milliseconds: 10000
