# Edit with your own configuration

application:
  host: 0.0.0.0

database:
  require_ssl: true

email_client:
  base_url: https://api.postmarkapp.com
  # `APP_EMAIL_CLIENT__SENDER_EMAIL` and `APP_EMAIL_CLIENT__AUTHORIZATION_TOKEN` should be set as environment variables.
