# Override the settings with your own configuration.
# Alternatively, set them as environment variables.

application:
  host: 0.0.0.0
  # port:
  # base_url:
  # hmac_secret:

database:
  require_ssl: true
  # host:
  # port:
  # username:
  # password:
  # database_name:

email_client:
  base_url: https://api.postmarkapp.com
  # sender_email:
  # authorization_token:

# redis_url:
